files:
  - source: /en/1
    translation: /%two_letters_code%/1/%original_file_name%
  - source: /en/2
    translation: /%two_letters_code%/2/%original_file_name%
  - source: /en/3
    translation: /%two_letters_code%/3/%original_file_name%
  - source: /en/4
    translation: /%two_letters_code%/4/%original_file_name%
  - source: /en/5
    translation: /%two_letters_code%/5/%original_file_name%
  - source: /en/6
    translation: /%two_letters_code%/6/%original_file_name%
  - source: /en/10
    translation: /%two_letters_code%/6/%original_file_name%
  - source: /en/11
    translation: /%two_letters_code%/6/%original_file_name%
  - source: /en/12
    translation: /%two_letters_code%/6/%original_file_name%
  - source: /en/13
    translation: /%two_letters_code%/6/%original_file_name%
  - source: /en/14
    translation: /%two_letters_code%/6/%original_file_name%
  - source: /en/15
    translation: /%two_letters_code%/6/%original_file_name%
  - source: /en/16
    translation: /%two_letters_code%/6/%original_file_name%
  - source: /en/17
    translation: /%two_letters_code%/6/%original_file_name%
  - source: /en/18
    translation: /%two_letters_code%/6/%original_file_name%
  - source: /en/19
    translation: /%two_letters_code%/6/%original_file_name%
  - source: /en/20
    translation: /%two_letters_code%/6/%original_file_name%
  - source: /en/21
    translation: /%two_letters_code%/6/%original_file_name%
  - source: /en/22
    translation: /%two_letters_code%/6/%original_file_name%
  - source: /en/23
    translation: /%two_letters_code%/6/%original_file_name%
  - source: /en/24
    translation: /%two_letters_code%/6/%original_file_name%
  - source: /en/25
    translation: /%two_letters_code%/6/%original_file_name%
  - source: /en/26
    translation: /%two_letters_code%/6/%original_file_name%
  - source: /en/27
    translation: /%two_letters_code%/6/%original_file_name%
  - source: /en/28
    translation: /%two_letters_code%/6/%original_file_name%
  - source: /en/*
    ignore:
      - index.ts
    translation: /%two_letters_code%/%original_file_name%
